### ISSUE TITLE
Remove the personal Twitter account

### ISSUE THREAD

**Issue by RicoToothless** [iii-cutting-edge-tech-lab/old-buddies-website#4]
Please remove the personal Twitter account
https://github.com/iii-cutting-edge-tech-lab/old-buddies-website/blob/main/config.toml#L19

Or maybe can reference to `III Old Buddies` Facebook group URL?
https://www.facebook.com/groups/349727092633390

**Comment by neilkuan** [comment]
great , I will do it .
